server:
  port: 8086

spring:
  jackson:
    time-zone: Asia/Shanghai

user-info:
  name: zhangsan
  age: 50
  marital: true
  weight: 68.5
  birth: 1970/10/02
  email: asdf@qq.com
  obj:
    key1: va1
    key2: va2
  hobby:
    - smoke
    - drink
    - perm
  pets:
    - name: mimi
      breed: cat
    - name: laifu
      breed: dog
  maps:
    key1:
      ck1: cv1
      ck2: 2
    key2: va2

